### ISSUE TITLE
"Login with Instagram" failed.

### ISSUE THREAD

**Issue by thaewrapt** [piratus/wholikes#1]
Clicking on "Login with Instagram" button fails, redirecting to http://wholikes.piratus.net/undefined URL.

**Comment by piratus** [comment]
Since Instagram updated their API terms, applications are in a "sandbox" until approved by Instagram.  The main issue is that they don't approve applications that are still in development, so for now service is basically not working.

However, I've added you as a tester for the app. You should see an invite here https://www.instagram.com/developer/clients/sandbox_invites/

**Comment by thaewrapt** [comment]
Invite accepted, tnx!
